ARG TAG=local
FROM nicfit/alpine-base:${TAG}
MAINTAINER <nicfit@gmail.com>

RUN apk add --no-cache python3 &&\
            python3 -m ensurepip &&\
    ln -s $(which python3)  $(dirname `which python3`)/python &&\
    ln -s $(which pip3)  $(dirname `which pip3`)/pip
